import {
  MdDirectionsCar,
  MdHealthAndSafety,
  MdHome,
  MdArrowForward,
  MdHourglassEmpty,
  MdDescription,
  MdThumbUp,
  MdThumbDown,
  MdCheckCircle,
  MdPeople,
  MdNotificationsActive,
} from 'react-icons/md';

export const ESTADO_CONFIG = {
  enviado: { label: 'Enviado', badge: 'bg-primary/10 text-primary', dot: 'bg-primary', icon: MdArrowForward },
  evaluacion: {
    label: 'En evaluación',
    badge: 'bg-amber-100 text-amber-700',
    dot: 'bg-amber-400',
    icon: MdHourglassEmpty,
  },
  docs: { label: 'Documentación', badge: 'bg-sky-100 text-sky-700', dot: 'bg-sky-400', icon: MdDescription },
  aprobado: { label: 'Aprobado', badge: 'bg-emerald-100 text-emerald-700', dot: 'bg-emerald-500', icon: MdThumbUp },
  rechazado: { label: 'Rechazado', badge: 'bg-rose-100 text-rose-600', dot: 'bg-rose-400', icon: MdThumbDown },
};

export const HISTORIAL_TIPO = {
  registro: { bg: 'bg-primary/10', text: 'text-primary', icon: MdCheckCircle },
  asignacion: { bg: 'bg-amber-100', text: 'text-amber-600', icon: MdPeople },
  solicitud: { bg: 'bg-rose-100', text: 'text-rose-500', icon: MdNotificationsActive },
  documento: { bg: 'bg-sky-100', text: 'text-sky-600', icon: MdDescription },
  aprobacion: { bg: 'bg-emerald-100', text: 'text-emerald-600', icon: MdThumbUp },
  rechazo: { bg: 'bg-rose-100', text: 'text-rose-500', icon: MdThumbDown },
};

export const SINIESTROS = [
  {
    id: 'SIN-2024-10482',
    polizaId: 'POL-2024-00182',
    polizaLabel: 'Seguro de Auto',
    polizaIcon: MdDirectionsCar,
    accentBg: 'bg-primary/10',
    accentText: 'text-primary',
    tipo: 'Accidente de tránsito',
    fecha: '12/04/2024',
    hora: '14:35',
    lugar: 'Av. Javier Prado 1280, Miraflores',
    desc: 'Colisión por alcance en semáforo. Daños en paragolpes trasero y luz izquierda. Sin lesionados.',
    estado: 'evaluacion',
    stepActual: 2,
    ajustador: 'Carlos Mendoza',
    ajustadorEmail: 'c.mendoza@segurosplus.pe',
    ajustadorPhone: '+51 987 654 321',
    monto: 'S/ 4,200',
    evidencias: ['Foto frontal.jpg', 'Foto lateral.jpg', 'Parte policial.pdf'],
    pendiente: 'Adjunta el presupuesto del taller autorizado para continuar con la evaluación.',
    timeline: [
      {
        estado: 'Enviado',
        fecha: '12/04/2024 14:50',
        completado: true,
        comentario: 'Reporte recibido y registrado en el sistema.',
      },
      {
        estado: 'En evaluación',
        fecha: '13/04/2024 09:00',
        completado: true,
        comentario: 'Caso asignado al ajustador Carlos Mendoza.',
      },
      {
        estado: 'Documentación',
        fecha: '14/04/2024 11:30',
        completado: false,
        activo: true,
        comentario: 'Se requiere presupuesto del taller autorizado.',
      },
      { estado: 'Aprobación', fecha: '—', completado: false, comentario: '' },
      { estado: 'Resolución', fecha: '—', completado: false, comentario: '' },
    ],
    historial: [
      {
        fecha: '14/04/2024',
        hora: '11:30',
        tipo: 'solicitud',
        texto: 'Se solicita adjuntar presupuesto del taller autorizado.',
        autor: 'Carlos Mendoza',
      },
      {
        fecha: '13/04/2024',
        hora: '09:00',
        tipo: 'asignacion',
        texto: 'Caso asignado al ajustador Carlos Mendoza para evaluación en campo.',
        autor: 'Sistema',
      },
      {
        fecha: '12/04/2024',
        hora: '14:50',
        tipo: 'registro',
        texto: 'Siniestro registrado correctamente en el sistema.',
        autor: 'Sistema',
      },
    ],
  },
  {
    id: 'SIN-2024-09871',
    polizaId: 'POL-2023-00891',
    polizaLabel: 'Seguro de Salud',
    polizaIcon: MdHealthAndSafety,
    accentBg: 'bg-emerald-100',
    accentText: 'text-emerald-600',
    tipo: 'Emergencia médica',
    fecha: '02/03/2024',
    hora: '08:10',
    lugar: 'Clínica San Felipe, Jesús María',
    desc: 'Hospitalización de 3 días por apendicitis aguda. Cirugía laparoscópica realizada el 03/03/2024.',
    estado: 'aprobado',
    stepActual: 4,
    ajustador: 'Ana Torres',
    ajustadorEmail: 'a.torres@segurosplus.pe',
    ajustadorPhone: '+51 976 543 210',
    monto: 'S/ 12,800',
    evidencias: ['Alta médica.pdf', 'Facturas clínica.pdf', 'Informe quirúrgico.pdf'],
    pendiente: null,
    timeline: [
      {
        estado: 'Enviado',
        fecha: '02/03/2024 08:20',
        completado: true,
        comentario: 'Reporte de emergencia médica recibido.',
      },
      {
        estado: 'En evaluación',
        fecha: '02/03/2024 10:00',
        completado: true,
        comentario: 'Revisión de cobertura iniciada por Ana Torres.',
      },
      {
        estado: 'Documentación',
        fecha: '04/03/2024 09:00',
        completado: true,
        comentario: 'Documentación completa recibida y verificada.',
      },
      {
        estado: 'Aprobación',
        fecha: '06/03/2024 15:00',
        completado: true,
        comentario: 'Reembolso aprobado por S/ 12,800.',
      },
      { estado: 'Resolución', fecha: '—', completado: false, comentario: '' },
    ],
    historial: [
      {
        fecha: '06/03/2024',
        hora: '15:00',
        tipo: 'aprobacion',
        texto: 'Reembolso aprobado por S/ 12,800. Se procesará en 3-5 días hábiles.',
        autor: 'Ana Torres',
      },
      {
        fecha: '04/03/2024',
        hora: '09:00',
        tipo: 'documento',
        texto: 'Documentación completa recibida: alta médica, facturas y informe quirúrgico.',
        autor: 'Sistema',
      },
      {
        fecha: '02/03/2024',
        hora: '10:00',
        tipo: 'asignacion',
        texto: 'Caso asignado a Ana Torres, especialista en siniestros de salud.',
        autor: 'Sistema',
      },
      {
        fecha: '02/03/2024',
        hora: '08:20',
        tipo: 'registro',
        texto: 'Emergencia médica registrada. Prioridad alta.',
        autor: 'Sistema',
      },
    ],
  },
  {
    id: 'SIN-2023-07654',
    polizaId: 'POL-2022-00345',
    polizaLabel: 'Seguro de Hogar',
    polizaIcon: MdHome,
    accentBg: 'bg-amber-100',
    accentText: 'text-amber-600',
    tipo: 'Daños a propiedad',
    fecha: '18/11/2023',
    hora: '21:00',
    lugar: 'Av. Javier Prado 1280, Miraflores',
    desc: 'Inundación por rotura de tubería en el baño principal. Daños en piso, paredes y muebles del dormitorio.',
    estado: 'rechazado',
    stepActual: 4,
    ajustador: 'Luis Vargas',
    ajustadorEmail: 'l.vargas@segurosplus.pe',
    ajustadorPhone: '+51 965 432 109',
    monto: '—',
    evidencias: ['Fotos daños.jpg', 'Informe técnico.pdf'],
    pendiente: null,
    timeline: [
      { estado: 'Enviado', fecha: '18/11/2023 22:00', completado: true, comentario: 'Reporte de daños recibido.' },
      {
        estado: 'En evaluación',
        fecha: '20/11/2023 09:00',
        completado: true,
        comentario: 'Inspección en domicilio programada.',
      },
      {
        estado: 'Documentación',
        fecha: '22/11/2023 14:00',
        completado: true,
        comentario: 'Inspección realizada. Informe técnico generado.',
      },
      {
        estado: 'Aprobación',
        fecha: '28/11/2023 10:00',
        completado: true,
        comentario: 'Caso rechazado por exclusión de cobertura.',
      },
      { estado: 'Resolución', fecha: '—', completado: false, comentario: '' },
    ],
    historial: [
      {
        fecha: '28/11/2023',
        hora: '10:00',
        tipo: 'rechazo',
        texto: 'Caso rechazado. La rotura de tuberías por desgaste crónico está excluida de la póliza Estándar.',
        autor: 'Luis Vargas',
      },
      {
        fecha: '22/11/2023',
        hora: '14:00',
        tipo: 'documento',
        texto: 'Inspección en domicilio completada. Daños confirmados por desgaste de tubería.',
        autor: 'Luis Vargas',
      },
      {
        fecha: '18/11/2023',
        hora: '22:00',
        tipo: 'registro',
        texto: 'Siniestro registrado. Inspección programada para el 20/11/2023.',
        autor: 'Sistema',
      },
    ],
  },
];
