apiVersion: 1

contactPoints:
  - orgId: 1
    name: serena-alertas
    receivers:
      - uid: serena-alertas-receiver
        type: email
        settings:
          addresses: admin@serena-seguros.com
          singleEmail: false
        disableResolveMessage: false

policies:
  - orgId: 1
    receiver: serena-alertas
    group_by: ['container_name']
    group_wait: 30s
    group_interval: 5m
    repeat_interval: 1h
