import {
  MdDirectionsCar,
  MdHealthAndSafety,
  MdHome,
  MdVerified,
  MdArticle,
  MdReceiptLong,
  MdDescription,
  MdPictureAsPdf,
  MdImage,
} from 'react-icons/md';

export const TIPO_CONFIG = {
  poliza: {
    label: 'Póliza',
    badge: 'bg-primary/10 text-primary',
    dot: 'bg-primary',
    iconBg: 'bg-primary/10',
    iconColor: 'text-primary',
    icon: MdVerified,
  },
  contrato: {
    label: 'Contrato',
    badge: 'bg-sky-100 text-sky-700',
    dot: 'bg-sky-400',
    iconBg: 'bg-sky-100',
    iconColor: 'text-sky-600',
    icon: MdArticle,
  },
  comprobante: {
    label: 'Comprobante',
    badge: 'bg-emerald-100 text-emerald-700',
    dot: 'bg-emerald-500',
    iconBg: 'bg-emerald-100',
    iconColor: 'text-emerald-600',
    icon: MdReceiptLong,
  },
  evidencia: {
    label: 'Evidencia',
    badge: 'bg-amber-100 text-amber-700',
    dot: 'bg-amber-400',
    iconBg: 'bg-amber-100',
    iconColor: 'text-amber-600',
    icon: MdDescription,
  },
};

export const EXT_ICON = {
  pdf: MdPictureAsPdf,
  jpg: MdImage,
  png: MdImage,
};

export const CATEGORIAS = [
  { id: 'todas', label: 'Todos' },
  { id: 'poliza', label: 'Pólizas' },
  { id: 'contrato', label: 'Contratos' },
  { id: 'comprobante', label: 'Comprobantes' },
  { id: 'evidencia', label: 'Evidencias' },
];

export const DOCUMENTOS = [
  // Pólizas
  {
    id: 'DOC-0001',
    nombre: 'Póliza de Seguro de Auto',
    tipo: 'poliza',
    extension: 'pdf',
    tamaño: '1.2 MB',
    fecha: '01/01/2024',
    fechaTs: 20240101,
    polizaId: 'POL-2024-00182',
    polizaLabel: 'Seguro de Auto',
    polizaIcon: MdDirectionsCar,
    accentBg: 'bg-primary/10',
    accentText: 'text-primary',
    siniestroId: null,
    importante: true,
    nuevo: false,
    descripcion: 'Contrato completo de póliza. Plan Cobertura Total · Vigencia 2024.',
  },
  {
    id: 'DOC-0002',
    nombre: 'Condiciones generales Auto',
    tipo: 'contrato',
    extension: 'pdf',
    tamaño: '3.8 MB',
    fecha: '01/01/2024',
    fechaTs: 20240101,
    polizaId: 'POL-2024-00182',
    polizaLabel: 'Seguro de Auto',
    polizaIcon: MdDirectionsCar,
    accentBg: 'bg-primary/10',
    accentText: 'text-primary',
    siniestroId: null,
    importante: false,
    nuevo: false,
    descripcion: 'Términos, exclusiones y condiciones del plan Cobertura Total.',
  },
  {
    id: 'DOC-0003',
    nombre: 'Póliza de Seguro de Salud',
    tipo: 'poliza',
    extension: 'pdf',
    tamaño: '980 KB',
    fecha: '15/06/2023',
    fechaTs: 20230615,
    polizaId: 'POL-2023-00891',
    polizaLabel: 'Seguro de Salud',
    polizaIcon: MdHealthAndSafety,
    accentBg: 'bg-emerald-100',
    accentText: 'text-emerald-600',
    siniestroId: null,
    importante: true,
    nuevo: false,
    descripcion: 'Contrato completo de póliza. Plan Familiar Plus · Vigencia 2023–2024.',
  },
  {
    id: 'DOC-0004',
    nombre: 'Póliza de Seguro de Hogar',
    tipo: 'poliza',
    extension: 'pdf',
    tamaño: '870 KB',
    fecha: '10/03/2022',
    fechaTs: 20220310,
    polizaId: 'POL-2022-00345',
    polizaLabel: 'Seguro de Hogar',
    polizaIcon: MdHome,
    accentBg: 'bg-amber-100',
    accentText: 'text-amber-600',
    siniestroId: null,
    importante: true,
    nuevo: false,
    descripcion: 'Contrato completo de póliza. Plan Estándar · Vigencia 2022–2024.',
  },
  // Comprobantes
  {
    id: 'DOC-0005',
    nombre: 'Comprobante de pago · Marzo 2024',
    tipo: 'comprobante',
    extension: 'pdf',
    tamaño: '210 KB',
    fecha: '18/03/2024',
    fechaTs: 20240318,
    polizaId: 'POL-2024-00182',
    polizaLabel: 'Seguro de Auto',
    polizaIcon: MdDirectionsCar,
    accentBg: 'bg-primary/10',
    accentText: 'text-primary',
    siniestroId: null,
    importante: false,
    nuevo: true,
    descripcion: 'Comprobante de cuota 3/12. Visa •••• 4821. S/ 890.00.',
  },
  {
    id: 'DOC-0006',
    nombre: 'Comprobante de pago · Feb 2024',
    tipo: 'comprobante',
    extension: 'pdf',
    tamaño: '198 KB',
    fecha: '14/02/2024',
    fechaTs: 20240214,
    polizaId: 'POL-2023-00891',
    polizaLabel: 'Seguro de Salud',
    polizaIcon: MdHealthAndSafety,
    accentBg: 'bg-emerald-100',
    accentText: 'text-emerald-600',
    siniestroId: null,
    importante: false,
    nuevo: false,
    descripcion: 'Comprobante de cuota 1/6. Transferencia BCP. S/ 340.00.',
  },
  {
    id: 'DOC-0007',
    nombre: 'Comprobante de pago · Ene 2024',
    tipo: 'comprobante',
    extension: 'pdf',
    tamaño: '201 KB',
    fecha: '28/01/2024',
    fechaTs: 20240128,
    polizaId: 'POL-2022-00345',
    polizaLabel: 'Seguro de Hogar',
    polizaIcon: MdHome,
    accentBg: 'bg-amber-100',
    accentText: 'text-amber-600',
    siniestroId: null,
    importante: false,
    nuevo: false,
    descripcion: 'Comprobante de cuota 7/12. Yape. S/ 210.00.',
  },
  // Siniestros
  {
    id: 'DOC-0008',
    nombre: 'Parte policial · SIN-2024-10482',
    tipo: 'evidencia',
    extension: 'pdf',
    tamaño: '540 KB',
    fecha: '12/04/2024',
    fechaTs: 20240412,
    polizaId: 'POL-2024-00182',
    polizaLabel: 'Seguro de Auto',
    polizaIcon: MdDirectionsCar,
    accentBg: 'bg-primary/10',
    accentText: 'text-primary',
    siniestroId: 'SIN-2024-10482',
    importante: false,
    nuevo: true,
    descripcion: 'Parte policial del accidente de tránsito. Av. Javier Prado, 12/04/2024.',
  },
  {
    id: 'DOC-0009',
    nombre: 'Foto frontal · SIN-2024-10482',
    tipo: 'evidencia',
    extension: 'jpg',
    tamaño: '2.1 MB',
    fecha: '12/04/2024',
    fechaTs: 20240412,
    polizaId: 'POL-2024-00182',
    polizaLabel: 'Seguro de Auto',
    polizaIcon: MdDirectionsCar,
    accentBg: 'bg-primary/10',
    accentText: 'text-primary',
    siniestroId: 'SIN-2024-10482',
    importante: false,
    nuevo: true,
    descripcion: 'Fotografía frontal del vehículo tras la colisión.',
  },
  {
    id: 'DOC-0010',
    nombre: 'Alta médica · SIN-2024-09871',
    tipo: 'evidencia',
    extension: 'pdf',
    tamaño: '320 KB',
    fecha: '05/03/2024',
    fechaTs: 20240305,
    polizaId: 'POL-2023-00891',
    polizaLabel: 'Seguro de Salud',
    polizaIcon: MdHealthAndSafety,
    accentBg: 'bg-emerald-100',
    accentText: 'text-emerald-600',
    siniestroId: 'SIN-2024-09871',
    importante: false,
    nuevo: false,
    descripcion: 'Alta médica tras hospitalización. Clínica San Felipe, 05/03/2024.',
  },
  {
    id: 'DOC-0011',
    nombre: 'Informe quirúrgico · SIN-2024-09871',
    tipo: 'evidencia',
    extension: 'pdf',
    tamaño: '415 KB',
    fecha: '04/03/2024',
    fechaTs: 20240304,
    polizaId: 'POL-2023-00891',
    polizaLabel: 'Seguro de Salud',
    polizaIcon: MdHealthAndSafety,
    accentBg: 'bg-emerald-100',
    accentText: 'text-emerald-600',
    siniestroId: 'SIN-2024-09871',
    importante: false,
    nuevo: false,
    descripcion: 'Informe de cirugía laparoscópica. Clínica San Felipe.',
  },
  {
    id: 'DOC-0012',
    nombre: 'Informe técnico · SIN-2023-07654',
    tipo: 'evidencia',
    extension: 'pdf',
    tamaño: '760 KB',
    fecha: '22/11/2023',
    fechaTs: 20231122,
    polizaId: 'POL-2022-00345',
    polizaLabel: 'Seguro de Hogar',
    polizaIcon: MdHome,
    accentBg: 'bg-amber-100',
    accentText: 'text-amber-600',
    siniestroId: 'SIN-2023-07654',
    importante: false,
    nuevo: false,
    descripcion: 'Informe de inspección técnica. Daños por rotura de tubería.',
  },
];
