import {
  MdDirectionsCar,
  MdHealthAndSafety,
  MdHome,
  MdHourglassEmpty,
  MdWarningAmber,
  MdCheckCircle,
  MdCreditCard,
  MdAccountBalance,
  MdPhoneAndroid,
  MdPayment,
} from 'react-icons/md';

export const ESTADO_CONFIG = {
  pendiente: {
    label: 'Pendiente',
    badge: 'bg-amber-100 text-amber-700',
    dot: 'bg-amber-400',
    icon: MdHourglassEmpty,
  },
  vencido: {
    label: 'Vencido',
    badge: 'bg-rose-100 text-rose-600',
    dot: 'bg-rose-400',
    icon: MdWarningAmber,
  },
  pagado: {
    label: 'Pagado',
    badge: 'bg-emerald-100 text-emerald-700',
    dot: 'bg-emerald-500',
    icon: MdCheckCircle,
  },
};

export const METODOS_PAGO = [
  { id: 'visa', label: 'Tarjeta de crédito', sub: 'Visa / Mastercard', icon: MdCreditCard },
  { id: 'transferencia', label: 'Transferencia', sub: 'Banco BCP, Interbank…', icon: MdAccountBalance },
  { id: 'yape', label: 'Yape / Plin', sub: 'Pago instantáneo', icon: MdPhoneAndroid },
  { id: 'debito', label: 'Tarjeta de débito', sub: 'Débito inmediato', icon: MdPayment },
];

export const CUOTAS = [
  {
    id: 'CUO-2024-00182-04',
    polizaId: 'POL-2024-00182',
    polizaLabel: 'Seguro de Auto',
    polizaIcon: MdDirectionsCar,
    accentBg: 'bg-primary/10',
    accentText: 'text-primary',
    numeroCuota: 4,
    totalCuotas: 12,
    monto: 'S/ 890.00',
    montoNum: 890.0,
    vencimiento: '20/04/2024',
    diasRestantes: 2,
    estado: 'pendiente',
    periodo: 'Abril 2024',
    descripcion: 'Cuota mensual · Plan Cobertura Total',
  },
  {
    id: 'CUO-2024-00182-03',
    polizaId: 'POL-2024-00182',
    polizaLabel: 'Seguro de Auto',
    polizaIcon: MdDirectionsCar,
    accentBg: 'bg-primary/10',
    accentText: 'text-primary',
    numeroCuota: 3,
    totalCuotas: 12,
    monto: 'S/ 890.00',
    montoNum: 890.0,
    vencimiento: '20/03/2024',
    diasRestantes: null,
    estado: 'pagado',
    periodo: 'Marzo 2024',
    descripcion: 'Cuota mensual · Plan Cobertura Total',
    comprobante: 'COMP-2024-03182.pdf',
    fechaPago: '18/03/2024',
    metodoPago: 'Visa •••• 4821',
  },
  {
    id: 'CUO-2024-09871-02',
    polizaId: 'POL-2023-00891',
    polizaLabel: 'Seguro de Salud',
    polizaIcon: MdHealthAndSafety,
    accentBg: 'bg-emerald-100',
    accentText: 'text-emerald-600',
    numeroCuota: 2,
    totalCuotas: 6,
    monto: 'S/ 340.00',
    montoNum: 340.0,
    vencimiento: '15/04/2024',
    diasRestantes: -3,
    estado: 'vencido',
    periodo: 'Abril 2024',
    descripcion: 'Cuota bimestral · Plan Familiar Plus',
  },
  {
    id: 'CUO-2024-09871-01',
    polizaId: 'POL-2023-00891',
    polizaLabel: 'Seguro de Salud',
    polizaIcon: MdHealthAndSafety,
    accentBg: 'bg-emerald-100',
    accentText: 'text-emerald-600',
    numeroCuota: 1,
    totalCuotas: 6,
    monto: 'S/ 340.00',
    montoNum: 340.0,
    vencimiento: '15/02/2024',
    diasRestantes: null,
    estado: 'pagado',
    periodo: 'Febrero 2024',
    descripcion: 'Cuota bimestral · Plan Familiar Plus',
    comprobante: 'COMP-2024-02891.pdf',
    fechaPago: '14/02/2024',
    metodoPago: 'Transferencia BCP',
  },
  {
    id: 'CUO-2022-00345-08',
    polizaId: 'POL-2022-00345',
    polizaLabel: 'Seguro de Hogar',
    polizaIcon: MdHome,
    accentBg: 'bg-amber-100',
    accentText: 'text-amber-600',
    numeroCuota: 8,
    totalCuotas: 12,
    monto: 'S/ 210.00',
    montoNum: 210.0,
    vencimiento: '30/04/2024',
    diasRestantes: 12,
    estado: 'pendiente',
    periodo: 'Abril 2024',
    descripcion: 'Cuota mensual · Plan Estándar',
  },
];

export const HISTORIAL = [
  {
    id: 'PAG-2024-0312',
    polizaLabel: 'Seguro de Auto',
    polizaIcon: MdDirectionsCar,
    accentBg: 'bg-primary/10',
    accentText: 'text-primary',
    monto: 'S/ 890.00',
    fecha: '18/03/2024',
    metodo: 'Visa •••• 4821',
    comprobante: 'COMP-2024-03182.pdf',
  },
  {
    id: 'PAG-2024-0215',
    polizaLabel: 'Seguro de Salud',
    polizaIcon: MdHealthAndSafety,
    accentBg: 'bg-emerald-100',
    accentText: 'text-emerald-600',
    monto: 'S/ 340.00',
    fecha: '14/02/2024',
    metodo: 'Transferencia BCP',
    comprobante: 'COMP-2024-02891.pdf',
  },
  {
    id: 'PAG-2024-0118',
    polizaLabel: 'Seguro de Hogar',
    polizaIcon: MdHome,
    accentBg: 'bg-amber-100',
    accentText: 'text-amber-600',
    monto: 'S/ 210.00',
    fecha: '28/01/2024',
    metodo: 'Yape',
    comprobante: 'COMP-2024-01345.pdf',
  },
];
